FROM oven/bun:1.3-debian

ARG ARG_REACT_APP_API_SERVER
ENV REACT_APP_API_SERVER=$ARG_REACT_APP_API_SERVER

ARG ARG_URL
ENV URL=$ARG_URL

ARG ARG_BASE_URL
ENV BASE_URL=$ARG_BASE_URL

ARG ARG_SIGN_IN_URL
ENV SIGN_IN_URL=$ARG_SIGN_IN_URL

ARG ARG_BOT_WS_URL
ENV BOT_WS_URL=$ARG_BOT_WS_URL

ARG ARG_API_URL_PREFIX
ENV API_URL_PREFIX=$ARG_API_URL_PREFIX

ARG ARG_UMAMI_WEBSITE_ID
ENV UMAMI_WEBSITE_ID=$ARG_UMAMI_WEBSITE_ID

ARG ARG_UMAMI_SCRIPT_URL
ENV UMAMI_SCRIPT_URL=$ARG_UMAMI_SCRIPT_URL

WORKDIR /docs

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile

COPY . .
RUN bun run build

EXPOSE 3000
CMD ["bun", "run", "serve"]
