FROM node:18.20

ARG ARG_REACT_APP_API_SERVER
ENV REACT_APP_API_SERVER=$ARG_REACT_APP_API_SERVER

ARG ARG_URL
ENV URL=$ARG_URL

ARG ARG_BASE_URL
ENV BASE_URL=$ARG_BASE_URL

ARG ARG_SIGN_IN_URL
ENV SIGN_IN_URL=$ARG_SIGN_IN_URL

ARG ARG_BOT_WS_URL
ENV BOT_WS_URL=$ARG_BOT_WS_URL

ARG ARG_API_URL_PREFIX
ENV API_URL_PREFIX=$ARG_API_URL_PREFIX

ARG ARG_UMAMI_WEBSITE_ID
ENV UMAMI_WEBSITE_ID=$ARG_UMAMI_WEBSITE_ID

ARG ARG_UMAMI_SCRIPT_URL
ENV UMAMI_SCRIPT_URL=$ARG_UMAMI_SCRIPT_URL

# Install bun
RUN curl -fsSL https://bun.sh/install | bash
ENV BUN_INSTALL="/root/.bun"
ENV PATH="$BUN_INSTALL/bin:$PATH"

WORKDIR /docs

COPY package.json ./
COPY bun.lock ./
RUN bun install --frozen-lockfile

COPY . .
# Make cache folder if not exists.
RUN mkdir -p .cache
RUN mv .cache node_modules
RUN bun run build

EXPOSE 3000
CMD ["bun", "run", "serve"]
