export URL="http://localhost:3000"
export BASE_URL="/"
export SIGN_IN_URL="http://localhost:3001/signin"
export BOT_WS_URL="wss://localhost:9001/ai-bot-ws/"
export API_URL_PREFIX="https://v2.postgres.ai/api/general"