import React from 'react';
import {useDoc} from '@docusaurus/plugin-content-docs/client';
import ContentActions from '@site/src/components/ContentActions';

export default function DocsActions(): JSX.Element | null {
  const {metadata} = useDoc();
  
  // metadata.editUrl is correctly generated by Docusaurus with the actual filename
  // e.g., "https://gitlab.com/postgres-ai/docs/-/edit/master/docs/monitoring/dashboards/04-wait-events.md"
  const editUrl = metadata.editUrl;
  
  if (!editUrl) {
    return null;
  }
  
  // Extract the relative path from the editUrl to construct the raw URL
  // editUrl format: https://gitlab.com/postgres-ai/docs/-/edit/master/docs/path/to/file.md
  // We need to extract "path/to/file.md" from after "/master/docs/"
  const match = editUrl.match(/\/master\/docs\/(.+\.md)$/);
  if (!match) {
    return null;
  }
  
  const relativePath = match[1];
  const rawUrl = `/raw/docs/${relativePath}`;
  
  // Intentionally use blob (view) URL instead of edit URL.
  // This lets users see the file first and choose their preferred editing method:
  // Web IDE, single file editor, clone & edit locally, etc.
  const viewUrl = editUrl.replace('/-/edit/', '/-/blob/');

  return <ContentActions rawUrl={rawUrl} editUrl={viewUrl} />;
}
